In [1]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('./Column-Correct-Data/new_2024-2025.csv')

In [20]:
df.count()

S.No                                                                                     736
STATE                                                                                    735
DISTRICT                                                                                 735
ASSESSMENT UNIT                                                                            0
Rainfall (mm)_C                                                                          729
                                                                                        ...
In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline      7
Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Fresh            4
Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Saline           0
Total Ground Water Availability in the area (ham)_Other Parameters Present_Fresh         729
Total Ground Water Availability in the area (ham)_Other Parameters Present_Saline        729
Length: 153, dtype: int64

In [21]:
df.head()

,S.No,STATE,DISTRICT,ASSESSMENT UNIT,Rainfall (mm)_C,Rainfall (mm)_NC,Rainfall (mm)_PQ,Rainfall (mm)_Total,Total Geographical Area (ha)_Recharge Worthy Area (ha)_C,Total Geographical Area (ha)_Recharge Worthy Area (ha)_NC,...,Total Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Total Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline,In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Total Ground Water Availability in the area (ham)_Other Parameters Present_Fresh,Total Ground Water Availability in the area (ham)_Other Parameters Present_Saline
0,1,ANDAMAN AND NICOBAR ISLANDS,N & M ANDAMAN,NaN,0.000000,3015.700000,0.0,3015.700000,0.0,58040.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14875.42,0.00
1,2,ANDAMAN AND NICOBAR ISLANDS,NICOBAR,NaN,0.000000,2805.200000,2805.2,2805.200000,0.0,37247.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9911.13,313.56
2,3,ANDAMAN AND NICOBAR ISLANDS,SOUTH ANDAMAN,NaN,0.000000,3015.700000,0.0,3015.700000,0.0,31524.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9717.96,0.00
3,4,ANDHRA PRADESH,Alluri Sitharama Raju,NaN,0.000000,1257.832755,0.0,1257.832755,0.0,639234.675995,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50117.56,0.00
4,5,ANDHRA PRADESH,Anakapalli,NaN,1205.747378,1176.354436,0.0,1182.552833,73066.0,273414.659920,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1317238.51,0.00

In [22]:
drop_col = ["ASSESSMENT UNIT", "S.No"]
df = df.drop(drop_col, axis=1)

In [24]:
df.head()

,STATE,DISTRICT,Rainfall (mm)_C,Rainfall (mm)_NC,Rainfall (mm)_PQ,Rainfall (mm)_Total,Total Geographical Area (ha)_Recharge Worthy Area (ha)_C,Total Geographical Area (ha)_Recharge Worthy Area (ha)_NC,Total Geographical Area (ha)_Recharge Worthy Area (ha)_PQ,Total Geographical Area (ha)_Recharge Worthy Area (ha)_Total,...,Total Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Total Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline,In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Total Ground Water Availability in the area (ham)_Other Parameters Present_Fresh,Total Ground Water Availability in the area (ham)_Other Parameters Present_Saline
0,ANDAMAN AND NICOBAR ISLANDS,N & M ANDAMAN,0.000000,3015.700000,0.0,3015.700000,0.0,58040.000000,0.0,58040.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14875.42,0.00
1,ANDAMAN AND NICOBAR ISLANDS,NICOBAR,0.000000,2805.200000,2805.2,2805.200000,0.0,37247.000000,828.0,38075.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9911.13,313.56
2,ANDAMAN AND NICOBAR ISLANDS,SOUTH ANDAMAN,0.000000,3015.700000,0.0,3015.700000,0.0,31524.000000,0.0,31524.000000,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9717.96,0.00
3,ANDHRA PRADESH,Alluri Sitharama Raju,0.000000,1257.832755,0.0,1257.832755,0.0,639234.675995,0.0,639234.675995,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50117.56,0.00
4,ANDHRA PRADESH,Anakapalli,1205.747378,1176.354436,0.0,1182.552833,73066.0,273414.659920,0.0,346480.659920,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1317238.51,0.00

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Columns: 151 entries, STATE to Total Ground Water Availability in the area (ham)_Other Parameters Present_Saline
dtypes: float64(146), object(5)
memory usage: 868.4+ KB

In [26]:
df.describe()

,Rainfall (mm)_C,Rainfall (mm)_NC,Rainfall (mm)_PQ,Rainfall (mm)_Total,Total Geographical Area (ha)_Recharge Worthy Area (ha)_C,Total Geographical Area (ha)_Recharge Worthy Area (ha)_NC,Total Geographical Area (ha)_Recharge Worthy Area (ha)_PQ,Total Geographical Area (ha)_Recharge Worthy Area (ha)_Total,Total Geographical Area (ha)_Hilly Area_Total,Total Geographical Area (ha)_Total_Total,...,Total Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Total Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline,In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Fresh,Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Saline,Total Ground Water Availability in the area (ham)_Other Parameters Present_Fresh,Total Ground Water Availability in the area (ham)_Other Parameters Present_Saline
count,729.000000,729.000000,729.000000,729.000000,7.360000e+02,7.290000e+02,7.290000e+02,7.290000e+02,7.290000e+02,7.290000e+02,...,6.880000e+02,0.0,4.0,0.0,11.0,7.0,4.0,0.0,7.290000e+02,7.290000e+02
mean,647.661149,1062.273500,95.309171,1252.232368,1.953735e+05,4.318300e+05,4.823249e+04,6.773120e+05,1.253653e+05,8.026773e+05,...,5.432040e+05,NaN,0.0,NaN,0.0,0.0,0.0,NaN,4.543159e+05,1.427336e+04
std,622.103786,897.110366,313.351556,745.162140,2.650383e+06,5.827260e+06,6.680021e+05,9.137319e+06,1.696840e+06,1.082706e+07,...,7.270569e+06,NaN,0.0,NaN,0.0,0.0,0.0,NaN,6.164257e+06,2.023009e+05
min,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,0.0,NaN,0.0,0.0,0.0,NaN,0.000000e+00,0.000000e+00
25%,0.000000,325.850911,0.000000,777.222719,0.000000e+00,5.740000e+02,0.000000e+00,1.414030e+05,0.000000e+00,2.012000e+05,...,0.000000e+00,NaN,0.0,NaN,0.0,0.0,0.0,NaN,3.467529e+04,0.000000e+00
50%,711.117619,999.600000,0.000000,1074.100000,2.229550e+04,1.437250e+05,0.000000e+00,2.676400e+05,8.783000e+03,3.239549e+05,...,0.000000e+00,NaN,0.0,NaN,0.0,0.0,0.0,NaN,6.546286e+04,0.000000e+00
75%,1075.500000,1425.976376,0.000000,1445.098624,1.534861e+05,3.305682e+05,0.000000e+00,4.314300e+05,6.841100e+04,5.010420e+05,...,0.000000e+00,NaN,0.0,NaN,0.0,0.0,0.0,NaN,1.134197e+05,0.000000e+00
max,3583.672339,4419.644794,2805.200000,4419.644794,7.189744e+07,1.574020e+08,1.758074e+07,2.468802e+08,4.569565e+07,2.925759e+08,...,1.868622e+08,NaN,0.0,NaN,0.0,0.0,0.0,NaN,1.655982e+08,5.202640e+06